package company

import (
	"encoding/json"
	common2 "github.com/erply/api-go-wrapper/pkg/api/common"
)

type (
	//CompanyInfos ..
	Infos []Info
	//CompanyInfo ..
	Info struct {
		ID                 string `json:"id"`
		Name               string `json:"name"`
		Code               string `json:"code"`
		VAT                string `json:"VAT"`
		Phone              string `json:"phone"`
		Mobile             string `json:"mobile"`
		Fax                string `json:"fax"`
		Email              string `json:"email"`
		Web                string `json:"web"`
		BankAccountNumber  string `json:"bankAccountNumber"`
		BankName           string `json:"bankName"`
		BankSWIFT          string `json:"bankSWIFT"`
		BankIBAN           string `json:"bankIBAN"`
		BankAccountNumber2 string `json:"bankAccountNumber2"`
		BankName2          string `json:"bankName2"`
		BankSWIFT2         string `json:"bankSWIFT2"`
		BankIBAN2          string `json:"bankIBAN2"`
		Address            string `json:"address"`
		Country            string `json:"country"`

		//field for ConfParameters
		ConfParameters ConfParameter
	} //GetCompanyInfoResponse ...
	GetCompanyInfoResponse struct {
		Status       common2.Status `json:"status"`
		CompanyInfos Infos          `json:"records"`
	}
)

type (
	ConfParameter struct {
		Announcement      string `json:"invoice_announcement_eng"`
		CSVSeparator      string `json:"csv_field_separator"`
		DcMemberProductID string `json:"DC_MEMBER_PRODUCT_ID"`
		AccountBank       string `json:"account_bank"`
		AccountLinks      struct {
			Help           string `json:"help"`
			HelpPOS        string `json:"helpPOS"`
			KnowledgeBase  string `json:"knowledge_base"`
			TermsOfService string `json:"terms_of_service"`
		} `json:"account_links"`
		AccountReceivable        string `json:"account_receivable"`
		AccountStatsUpdated      string `json:"account_stats_updated"`
		AccountWarehouse         string `json:"account_warehouse"`
		AccountsReceivableListed string `json:"accounts_receivable_listed"`
		ActualReportsUsername    string `json:"actual_reports_username"`
		AdditionalModules        []struct {
			Enabled int64  `json:"enabled"`
			Name    string `json:"name"`
		} `json:"additionalModules"`
		AllowCreateInvForContactPerson                                   string      `json:"allowCreateInvForContactPerson"`
		AllowCopyingInvoiceNotes                                         string      `json:"allow_copying_invoice_notes"`
		AllowPackedByCopying                                             string      `json:"allow_packed_by_copying"`
		AllowPartialFulfilmentInReport                                   string      `json:"allow_partial_fulfilment_in_report"`
		AllowPayWithCheck                                                string      `json:"allow_pay_with_check"`
		AlwaysShowEekPricesOnInvoiceForm                                 string      `json:"always_show_eek_prices_on_invoice_form"`
		AppInterface                                                     string      `json:"app_interface"`
		ApplyPromotionsToZeroPriceProducts                               string      `json:"apply_promotions_to_zero_price_products"`
		BalanceStatementBody                                             string      `json:"balance_statement_body"`
		BalanceStatementBodyEng                                          string      `json:"balance_statement_body_eng"`
		BalanceStatementSubjectEng                                       string      `json:"balance_statement_subject_eng"`
		BalanceStatementText1                                            string      `json:"balance_statement_text1"`
		BalanceStatementText1Eng                                         string      `json:"balance_statement_text1_eng"`
		BalanceStatementText2                                            string      `json:"balance_statement_text2"`
		BalanceStatementText2Eng                                         string      `json:"balance_statement_text2_eng"`
		BarcodeCodeLength                                                string      `json:"barcode_code_length"`
		BarcodeConfiguration                                             string      `json:"barcode_configuration"`
		BarcodeIntro                                                     string      `json:"barcode_intro"`
		BarcodeMeasurementLength                                         string      `json:"barcode_measurement_length"`
		BarcodeOnInvwaybilldocument                                      string      `json:"barcode_on_invwaybilldocument"`
		BarcodeOnSalesDocuments                                          string      `json:"barcode_on_sales_documents"`
		BarcodeOnWaybilldocument                                         string      `json:"barcode_on_waybilldocument"`
		BarcodePricePrefix                                               string      `json:"barcode_price_prefix"`
		BarcodeType                                                      string      `json:"barcode_type"`
		BarcodeWeightDecimals                                            string      `json:"barcode_weight_decimals"`
		BarcodeWeightPrefix                                              string      `json:"barcode_weight_prefix"`
		BillingInvoiceUseTodaysDate                                      string      `json:"billing_invoice_use_todays_date"`
		Branding                                                         string      `json:"branding"`
		CashInoutOpenDrawer                                              string      `json:"cash_inout_open_drawer"`
		CashOutWarningInterval                                           string      `json:"cash_out_warning_interval"`
		CashOutWarningTreshold                                           string      `json:"cash_out_warning_treshold"`
		Code2OnSalesdocument                                             string      `json:"code2_on_salesdocument"`
		Code3OnSalesdocument                                             string      `json:"code3_on_salesdocument"`
		Code4OnSalesdocument                                             string      `json:"code4_on_salesdocument"`
		Code5OnSalesdocument                                             string      `json:"code5_on_salesdocument"`
		Code6OnSalesdocument                                             string      `json:"code6_on_salesdocument"`
		Code7OnSalesdocument                                             string      `json:"code7_on_salesdocument"`
		Code8OnSalesdocument                                             string      `json:"code8_on_salesdocument"`
		CodeOnInvoice                                                    string      `json:"code_on_invoice"`
		CodeOnPrcorder                                                   string      `json:"code_on_prcorder"`
		CodeOnReceipt                                                    string      `json:"code_on_receipt"`
		CodeOnSalesdocument                                              string      `json:"code_on_salesdocument"`
		CommissionMethod                                                 string      `json:"commission_method"`
		CommissionPercentage                                             string      `json:"commission_percentage"`
		CorrectionProductID                                              string      `json:"correctionProductId"`
		Country                                                          string      `json:"country"`
		CreditPaymentsAreCreatedCorrectly                                string      `json:"credit_payments_are_created_correctly"`
		CrossSellRelationshipOneWay                                      string      `json:"cross_sell_relationship_one_way"`
		CsvSeparator                                                     string      `json:"csv_separator"`
		CustomerCodeUnique                                               string      `json:"customer_code_unique"`
		CustomerDisplayCustomPanel                                       string      `json:"customer_display_custom_panel"`
		CustomerIsCompanyLabel                                           string      `json:"customer_is_company_label"`
		CustomerIsPersonLabel                                            string      `json:"customer_is_person_label"`
		CustomerManagerRightsUpdated                                     string      `json:"customer_manager_rights_updated"`
		DaDisableDiscountDisplay                                         string      `json:"da_disable_discount_display"`
		DateInstalled                                                    string      `json:"date_installed"`
		Dateformat                                                       string      `json:"dateformat"`
		DayStartendOpenDrawer                                            string      `json:"day_startend_open_drawer"`
		DefaultClientIDDat                                               string      `json:"default_client_idDat"`
		DefaultCurrency                                                  string      `json:"default_currency"`
		DefaultEuZeroVat                                                 string      `json:"default_eu_zero_vat"`
		DefaultExemptZeroVat                                             string      `json:"default_exempt_zero_vat"`
		DefaultLanguage                                                  string      `json:"default_language"`
		DefaultLaybyCancellationFee                                      string      `json:"default_layby_cancellation_fee"`
		DefaultLengthForColoring                                         string      `json:"default_length_for_coloring"`
		DefaultLengthForHaircuts                                         string      `json:"default_length_for_haircuts"`
		DefaultPeriodForBalanceStatements                                string      `json:"default_period_for_balance_statements"`
		DefaultPriceDecimals                                             string      `json:"default_price_decimals"`
		DefaultTaxFreeZeroVat                                            string      `json:"default_tax_free_zero_vat"`
		DefaultZeroVat                                                   string      `json:"default_zero_vat"`
		DisableShowInWebshopByDefault                                    string      `json:"disable_show_in_webshop_by_default"`
		DiscountPrintedOnInvoices                                        string      `json:"discount_printed_on_invoices"`
		DisplayCustomerBalanceOnInvoice                                  string      `json:"display_customer_balance_on_invoice"`
		DisplayPicturesOnQuotes                                          string      `json:"display_pictures_on_quotes"`
		DisplayReceivedPaymentsOnInvoice                                 string      `json:"display_received_payments_on_invoice"`
		DisplayReceivedPaymentsOnOrder                                   string      `json:"display_received_payments_on_order"`
		DoNotSendInvoiceToCustomerEmail                                  string      `json:"doNotSendInvoiceToCustomerEmail"`
		DoNotCreateAutomaticCreditRefund                                 string      `json:"do_not_create_automatic_credit_refund"`
		DoNotSelectAddressAutomatically                                  string      `json:"do_not_select_address_automatically"`
		DoNotSelectContactAutomatically                                  string      `json:"do_not_select_contact_automatically"`
		DoNotShowDiscountsOnCustomerCard                                 string      `json:"do_not_show_discounts_on_customer_card"`
		DoNotUseNumpad                                                   string      `json:"do_not_use_numpad"`
		EmployeeIdentifierOnReceipt                                      string      `json:"employee_identifier_on_receipt"`
		EmployeeIdentifierOnSalesDocument                                string      `json:"employee_identifier_on_sales_document"`
		EnableAutomaticVersionUpgrade                                    string      `json:"enable_automatic_version_upgrade"`
		EnableDeliveryDateTracking                                       string      `json:"enable_delivery_date_tracking"`
		ExpectedTransferAddVisaMcTogether                                string      `json:"expected_transfer_add_visa_mc_together"`
		ExportSalesReportToExcel                                         string      `json:"export_sales_report_to_excel"`
		ExtraField1IsActive                                              string      `json:"extra_field1_is_active"`
		ExtraField1LabelEng                                              string      `json:"extra_field1_label_eng"`
		Factoring                                                        string      `json:"factoring"`
		FinalPriceInputOnInvoice                                         string      `json:"final_price_input_on_invoice"`
		FiscalYearStartDate                                              string      `json:"fiscal_year_start_date"`
		FullImageDir                                                     string      `json:"full_image_dir"`
		GdprApprovalProcessEnabled                                       string      `json:"gdpr_approval_process_enabled"`
		GivexAdminID                                                     string      `json:"givex_admin_id"`
		GivexPayments                                                    string      `json:"givex_payments"`
		GoogleappsDefaultUsergroup                                       string      `json:"googleapps_default_usergroup"`
		HansaCardAccount                                                 string      `json:"hansa_card_account"`
		HansaCardCode                                                    string      `json:"hansa_card_code"`
		HansaCashAccount                                                 string      `json:"hansa_cash_account"`
		HansaCashCode                                                    string      `json:"hansa_cash_code"`
		HansaCreditCode                                                  string      `json:"hansa_credit_code"`
		HansaGoodsRevenueAccount                                         string      `json:"hansa_goods_revenue_account"`
		HansaIncludeProductCodes                                         string      `json:"hansa_include_product_codes"`
		HansaPayablesAccount                                             string      `json:"hansa_payables_account"`
		HansaReceivablesAccount                                          string      `json:"hansa_receivables_account"`
		HansaRoundingAccount                                             string      `json:"hansa_rounding_account"`
		HansaServicesRevenueAccount                                      string      `json:"hansa_services_revenue_account"`
		HansaWarehouseAccount                                            string      `json:"hansa_warehouse_account"`
		HideBoFunctionsAdminUserGroup                                    string      `json:"hide_bo_functions_admin_user_group"`
		HideBoFunctionsConfigurationCoupons                              string      `json:"hide_bo_functions_configuration_coupons"`
		HideBoFunctionsMenulinkPOS                                       string      `json:"hide_bo_functions_menulink_POS"`
		HideBoFunctionsMenulinkAccounting                                string      `json:"hide_bo_functions_menulink_accounting"`
		HideBoFunctionsMenulinkCustomersBalances                         string      `json:"hide_bo_functions_menulink_customers_balances"`
		HideBoFunctionsMenulinkInventoryExtraField1                      string      `json:"hide_bo_functions_menulink_inventory_extra_field_1"`
		HideBoFunctionsMenulinkInventoryExtraField2                      string      `json:"hide_bo_functions_menulink_inventory_extra_field_2"`
		HideBoFunctionsMenulinkInventoryExtraField3                      string      `json:"hide_bo_functions_menulink_inventory_extra_field_3"`
		HideBoFunctionsMenulinkInventoryExtraField4                      string      `json:"hide_bo_functions_menulink_inventory_extra_field_4"`
		HideBoFunctionsMenulinkInventoryImportProductsFromTXT            string      `json:"hide_bo_functions_menulink_inventory_import_products_from_TXT"`
		HideBoFunctionsMenulinkInventoryProductCategories                string      `json:"hide_bo_functions_menulink_inventory_product_categories"`
		HideBoFunctionsMenulinkInventoryStoreRegions                     string      `json:"hide_bo_functions_menulink_inventory_store_regions"`
		HideBoFunctionsMenulinkPurchaseExportPurchaseDocumentsAccounting string      `json:"hide_bo_functions_menulink_purchase_export_purchase_documents_accounting"`
		HideBoFunctionsMenulinkReportsFinance                            string      `json:"hide_bo_functions_menulink_reports_finance"`
		HideBoFunctionsMenulinkRetailChainAllPromotions                  string      `json:"hide_bo_functions_menulink_retail_chain_all_promotions"`
		HideBoFunctionsMenulinkRetailChainEmployees                      string      `json:"hide_bo_functions_menulink_retail_chain_employees"`
		HideBoFunctionsMenulinkRetailChainNewEmployee                    string      `json:"hide_bo_functions_menulink_retail_chain_new_employee"`
		HideBoFunctionsMenulinkRetailChainNewPromotion                   string      `json:"hide_bo_functions_menulink_retail_chain_new_promotion"`
		HideBoFunctionsMenulinkRetailChainPromotionTiers                 string      `json:"hide_bo_functions_menulink_retail_chain_promotion_tiers"`
		HideBoFunctionsMenulinkSalesFinance                              string      `json:"hide_bo_functions_menulink_sales_finance"`
		HideBoFunctionsSectionProductInfoDepositFee                      string      `json:"hide_bo_functions_section_product_info_deposit_fee"`
		HideBoFunctionsSectionProductInfoPriceCalculator                 string      `json:"hide_bo_functions_section_product_info_price_calculator"`
		HideBoFunctionsSectionProductInfoProductAvgprcprice              string      `json:"hide_bo_functions_section_product_info_product_avgprcprice"`
		HideBoFunctionsSectionProductInfoProductBackbarCharges           string      `json:"hide_bo_functions_section_product_info_product_backbar_charges"`
		HideBoFunctionsSectionProductInfoProductCode3                    string      `json:"hide_bo_functions_section_product_info_product_code3"`
		HideBoFunctionsSectionProductInfoProductContainerAmount          string      `json:"hide_bo_functions_section_product_info_product_container_amount"`
		HideBoFunctionsSectionProductInfoProductCostprice                string      `json:"hide_bo_functions_section_product_info_product_costprice"`
		HideBoFunctionsSectionProductInfoProductCountryID                string      `json:"hide_bo_functions_section_product_info_product_country_id"`
		HideBoFunctionsSectionProductInfoProductDelivery                 string      `json:"hide_bo_functions_section_product_info_product_delivery"`
		HideBoFunctionsSectionProductInfoProductManufacturer             string      `json:"hide_bo_functions_section_product_info_product_manufacturer"`
		HideBoFunctionsSectionProductInfoProductWarehouseLocationID      string      `json:"hide_bo_functions_section_product_info_product_warehouse_location_id"`
		HideBoFunctionsSectionProductInfoWarehousePrice                  string      `json:"hide_bo_functions_section_product_info_warehouse_price"`
		HideBoFunctionsSectionProductNetSalesPrice                       string      `json:"hide_bo_functions_section_product_net_sales_price"`
		HideBoFunctionsSectionProductProductTaxfree                      string      `json:"hide_bo_functions_section_product_product_taxfree"`
		HideBoFunctionsSectionProductSalesPrice                          string      `json:"hide_bo_functions_section_product_sales_price"`
		HideBoFunctionsSectionProductSupplierField                       string      `json:"hide_bo_functions_section_product_supplier_field"`
		HideBoFunctionsSectionProductTabAttributes                       string      `json:"hide_bo_functions_section_product_tab_attributes"`
		HideBoFunctionsSectionProductTabPackages                         string      `json:"hide_bo_functions_section_product_tab_packages"`
		HideBoFunctionsSectionProductTabProductFiles                     string      `json:"hide_bo_functions_section_product_tab_productFiles"`
		HideBoFunctionsSectionProductTabProductPictures                  string      `json:"hide_bo_functions_section_product_tab_productPictures"`
		HideBoFunctionsSectionProductTabProductComponentsSubsec          string      `json:"hide_bo_functions_section_product_tab_product_components_subsec"`
		HideBoFunctionsSectionProductTabProductPrcordersSubsec           string      `json:"hide_bo_functions_section_product_tab_product_prcorders_subsec"`
		HideBoFunctionsSectionProductTabWebFields                        string      `json:"hide_bo_functions_section_product_tab_web_fields"`
		HideBoFunctionsSectionProductTaxRate                             string      `json:"hide_bo_functions_section_product_tax_rate"`
		HideCustomerCompanyAddressOnReceipt                              string      `json:"hide_customer_company_address_on_receipt"`
		HideCustomerCompanyNameOnReceipt                                 string      `json:"hide_customer_company_name_on_receipt"`
		HideCustomerPersonAddressOnReceipt                               string      `json:"hide_customer_person_address_on_receipt"`
		HideCustomerPersonNameOnReceipt                                  string      `json:"hide_customer_person_name_on_receipt"`
		HideQrCodeOnSalesDocument                                        string      `json:"hide_qr_code_on_sales_document"`
		HideVerificationCodeOnReceipt                                    string      `json:"hide_verification_code_on_receipt"`
		ImportLinkInInvoiceMail                                          string      `json:"import_link_in_invoice_mail"`
		InventoryModulesRightsUpdated                                    string      `json:"inventory_modules_rights_updated"`
		InventoryModulesRightsUpdatedBerlin                              string      `json:"inventory_modules_rights_updated_berlin"`
		InventoryReportsRightsUpdated                                    string      `json:"inventory_reports_rights_updated"`
		InvoiceExtraFooterLine                                           string      `json:"invoiceExtraFooterLine"`
		InvoiceLogoURL                                                   string      `json:"invoiceLogoURL"`
		InvoiceSignatureURL                                              string      `json:"invoiceSignatureURL"`
		InvoiceAlgorithmVersion                                          int64       `json:"invoice_algorithm_version"`
		InvoiceAnnouncement                                              string      `json:"invoice_announcement"`
		InvoiceClientIsPayer                                             string      `json:"invoice_client_is_payer"`
		InvoiceGroupRowsByWaybill                                        string      `json:"invoice_group_rows_by_waybill"`
		InvoiceMailTemplate                                              string      `json:"invoice_mail_template"`
		InvoicePrintRows1p                                               string      `json:"invoice_print_rows1p"`
		InvoicePrintRowsNp                                               string      `json:"invoice_print_rowsNp"`
		InvoiceRounding                                                  string      `json:"invoice_rounding"`
		InvoiceStartNumber                                               string      `json:"invoice_start_number"`
		InvoiceWaybillsShowPriceWithTax                                  int64       `json:"invoice_waybills_show_price_with_tax"`
		InvoicerowsReturnReason                                          string      `json:"invoicerows_return_reason"`
		IPWhitelistingEnabled                                            string      `json:"ip_whitelisting_enabled"`
		IssuedCouponsDuration                                            string      `json:"issued_coupons_duration"`
		JavascriptPlugins                                                string      `json:"javascript_plugins"`
		JspluginAppstoreEnabled                                          string      `json:"jsplugin_appstore_enabled"`
		JspluginCdnEnabled                                               string      `json:"jsplugin_cdn_enabled"`
		JspluginImportEnabled                                            string      `json:"jsplugin_import_enabled"`
		JspluginPromotionsEnabled                                        string      `json:"jsplugin_promotions_enabled"`
		Langs                                                            string      `json:"langs"`
		Languages                                                        string      `json:"languages"`
		LocaleUsesPriceWithTax                                           int64       `json:"locale_uses_price_with_tax"`
		MailSubjectContainsCompanyName                                   string      `json:"mail_subject_contains_company_name"`
		MailtemplateDefaultEng                                           string      `json:"mailtemplate_default_eng"`
		MailtemplateInv10Eng                                             string      `json:"mailtemplate_inv10_eng"`
		MailtemplateInv1Eng                                              string      `json:"mailtemplate_inv1_eng"`
		MailtemplateInv2Eng                                              string      `json:"mailtemplate_inv2_eng"`
		MailtemplateInv3Eng                                              string      `json:"mailtemplate_inv3_eng"`
		MailtemplateInv4Eng                                              string      `json:"mailtemplate_inv4_eng"`
		MailtemplateInv5Eng                                              string      `json:"mailtemplate_inv5_eng"`
		MailtemplateInv7Eng                                              string      `json:"mailtemplate_inv7_eng"`
		MailtemplateInv8Eng                                              string      `json:"mailtemplate_inv8_eng"`
		MailtemplateInv9Eng                                              string      `json:"mailtemplate_inv9_eng"`
		MailtemplatePrcinv2Eng                                           string      `json:"mailtemplate_prcinv2_eng"`
		MailtemplatePrcinv3Eng                                           string      `json:"mailtemplate_prcinv3_eng"`
		MailtemplatePrcinv4Eng                                           string      `json:"mailtemplate_prcinv4_eng"`
		MainWarehouse                                                    string      `json:"main_warehouse"`
		MakeSalesReportsByRevenue                                        string      `json:"make_sales_reports_by_revenue"`
		MaskEmailAddressesInLog                                          string      `json:"mask_email_addresses_in_log"`
		MatrixUpdateCode                                                 string      `json:"matrix_update_code"`
		MatrixUpdateCode3                                                string      `json:"matrix_update_code3"`
		MatrixUpdateCode4                                                string      `json:"matrix_update_code4"`
		MatrixUpdateCode5                                                string      `json:"matrix_update_code5"`
		MatrixUpdateCode6                                                string      `json:"matrix_update_code6"`
		MatrixUpdateCode7                                                string      `json:"matrix_update_code7"`
		MatrixUpdateCode8                                                string      `json:"matrix_update_code8"`
		MatrixUpdateCommissionAmount                                     string      `json:"matrix_update_commission_amount"`
		MatrixUpdateCostprice                                            string      `json:"matrix_update_costprice"`
		MatrixUpdateIsactive                                             string      `json:"matrix_update_isactive"`
		MatrixUpdateName                                                 string      `json:"matrix_update_name"`
		MatrixUpdatePrice                                                string      `json:"matrix_update_price"`
		MatrixUpdateShowInWebshop                                        string      `json:"matrix_update_show_in_webshop"`
		MatrixUpdateVariationsAutomatically                              string      `json:"matrix_update_variations_automatically"`
		MatrixUpdateWarehouseLocation                                    string      `json:"matrix_update_warehouse_location"`
		NewInventoryStartDate                                            string      `json:"new_inventory_start_date"`
		NoBarcodeOnReceiptFooter                                         string      `json:"no_barcode_on_receipt_footer"`
		Numberformat                                                     string      `json:"numberformat"`
		OrderIsCompletedWhen                                             string      `json:"order_is_completed_when"`
		OrgIDDat                                                         string      `json:"org_idDat"`
		ParameterSetsRightsInitialized                                   string      `json:"parameter_sets_rights_initialized"`
		PartialFulfilmentSplitsOrder                                     string      `json:"partial_fulfilment_splits_order"`
		PaxPayments                                                      string      `json:"pax_payments"`
		PaymentDeadline                                                  string      `json:"payment_deadline"`
		PaymentInfoInTable                                               string      `json:"payment_info_in_table"`
		PaymentReminderBody                                              string      `json:"payment_reminder_body"`
		PaymentReminderBodyEng                                           string      `json:"payment_reminder_body_eng"`
		PaymentReminderShowOnlyOverdueInvoices                           string      `json:"payment_reminder_show_only_overdue_invoices"`
		PaymentReminderSubjectEng                                        string      `json:"payment_reminder_subject_eng"`
		PaymentReminderText1                                             string      `json:"payment_reminder_text1"`
		PaymentReminderText1Eng                                          string      `json:"payment_reminder_text1_eng"`
		PaymentReminderText2                                             string      `json:"payment_reminder_text2"`
		PaymentReminderText2Eng                                          string      `json:"payment_reminder_text2_eng"`
		PlgBackofficeChangeWbuDisableOrderSaveForUserGroups              string      `json:"plg_backoffice_change_wbu_disable_order_save_for_user_groups"`
		PlgSalesComparisonReportArTemplates                              string      `json:"plg_sales_comparison_report_ar_templates"`
		PluginAllowGiftcardButtonUsergroups                              string      `json:"plugin_allow_giftcard_button_usergroups"`
		PluginDscLoyaltyMembershipBaseURL                                string      `json:"plugin_dsc_loyalty_membership_base_url"`
		PluginDscMembershipGroupID                                       string      `json:"plugin_dsc_membership_group_id"`
		PluginDscMembershipProductID                                     string      `json:"plugin_dsc_membership_product_id"`
		PluginGivexincrenentProductID                                    string      `json:"plugin_givexincrenent_product_id"`
		PluginProductExportMicroserviceHeaders                           string      `json:"plugin_product_export_microservice_headers"`
		PluginProductExportMicroserviceURL                               string      `json:"plugin_product_export_microservice_url"`
		PluginPromotionsCustomTiers                                      string      `json:"plugin_promotions_custom_tiers"`
		PluginPromotionsDisableHqDelete                                  string      `json:"plugin_promotions_disable_hq_delete"`
		PluginPurchaseInvoiceAdditionalCostCorrectionProductID           string      `json:"plugin_purchase_invoice_additional_cost_correction_product_id"`
		PluginPurchaseInvoicePrintActualReportID                         string      `json:"plugin_purchase_invoice_print_actual_report_id"`
		PluginPurchaseOrderPrintActualReportID                           string      `json:"plugin_purchase_order_print_actual_report_id"`
		PluginQuickbooksExportEndpointURL                                string      `json:"plugin_quickbooks_export_endpoint_url"`
		PluginReorderWorksheetAPIEndpoint                                string      `json:"plugin_reorder_worksheet_api_endpoint"`
		PluginReorderWorksheetConfig                                     string      `json:"plugin_reorder_worksheet_config"`
		PluginSalesSummaryDscReportEndpointURL                           string      `json:"plugin_sales_summary_dsc_report_endpoint_url"`
		PluginSalesSummaryReportActualreportID                           string      `json:"plugin_sales_summary_report_actualreport_id"`
		PosAddRowsAutomatically                                          string      `json:"pos_add_rows_automatically"`
		PosAllowReturnCard                                               string      `json:"pos_allow_return_card"`
		PosAllowReturnCash                                               string      `json:"pos_allow_return_cash"`
		PosAllowReturnCheck                                              string      `json:"pos_allow_return_check"`
		PosAllowReturnGiftcardRegular                                    string      `json:"pos_allow_return_giftcard_regular"`
		PosAllowReturnGiftcardSerial                                     string      `json:"pos_allow_return_giftcard_serial"`
		PosAllowReturnReceiptCard                                        string      `json:"pos_allow_return_receipt_card"`
		PosAllowReturnReceiptCash                                        string      `json:"pos_allow_return_receipt_cash"`
		PosAllowReturnReceiptCheck                                       string      `json:"pos_allow_return_receipt_check"`
		PosAllowReturnReceiptGiftcardRegular                             string      `json:"pos_allow_return_receipt_giftcard_regular"`
		PosAllowReturnReceiptGiftcardSerial                              string      `json:"pos_allow_return_receipt_giftcard_serial"`
		PosAllowReturnReceiptStorecredit                                 string      `json:"pos_allow_return_receipt_storecredit"`
		PosAllowReturnReceiptStorecreditLimit                            string      `json:"pos_allow_return_receipt_storecredit_limit"`
		PosAllowReturnReceiptTip                                         string      `json:"pos_allow_return_receipt_tip"`
		PosAllowReturnStorecredit                                        string      `json:"pos_allow_return_storecredit"`
		PosAllowReturnTip                                                string      `json:"pos_allow_return_tip"`
		PosAllowSaleCard                                                 string      `json:"pos_allow_sale_card"`
		PosAllowSaleCash                                                 string      `json:"pos_allow_sale_cash"`
		PosAllowSaleCheck                                                string      `json:"pos_allow_sale_check"`
		PosAllowSaleGiftcardRegular                                      string      `json:"pos_allow_sale_giftcard_regular"`
		PosAllowSaleGiftcardSerial                                       string      `json:"pos_allow_sale_giftcard_serial"`
		PosAllowSaleStorecredit                                          string      `json:"pos_allow_sale_storecredit"`
		PosAllowSaleStorecreditLimit                                     string      `json:"pos_allow_sale_storecredit_limit"`
		PosAllowSaleTip                                                  string      `json:"pos_allow_sale_tip"`
		PosAskCustomerData                                               string      `json:"pos_ask_customer_data"`
		PosDefaultLanguage                                               string      `json:"pos_default_language"`
		PosGroupItemsTogether                                            string      `json:"pos_group_items_together"`
		PosOpeningRequired                                               string      `json:"pos_opening_required"`
		PosRequireEmail                                                  string      `json:"pos_require_email"`
		PosRequireFacebook                                               string      `json:"pos_require_facebook"`
		PosRequireTwitter                                                string      `json:"pos_require_twitter"`
		PosRequiredCustomerData                                          string      `json:"pos_required_customer_data"`
		PosTimeout                                                       string      `json:"pos_timeout"`
		PosUseGiftcardsWithSerialNumbers                                 string      `json:"pos_use_giftcards_with_serial_numbers"`
		PosVersion1Disabled                                              string      `json:"pos_version_1_disabled"`
		PosVersionTouchDisabled                                          string      `json:"pos_version_touch_disabled"`
		PosVersionWebDisabled                                            string      `json:"pos_version_web_disabled"`
		PositiveStockRequired                                            string      `json:"positive_stock_required"`
		PrcinvoiceSendPriceVarianceNoticeTo                              string      `json:"prcinvoice_send_price_variance_notice_to"`
		PrcinvoiceWithSalesprice                                         string      `json:"prcinvoice_with_salesprice"`
		PrcorderSendPriceVarianceNoticeTo                                string      `json:"prcorder_send_price_variance_notice_to"`
		PrcorderStatusWhenPartiallyReceived                              string      `json:"prcorder_status_when_partially_received"`
		PrcorderWithoutRegcode                                           string      `json:"prcorder_without_regcode"`
		PrcorderWithoutWarehouseLocation                                 string      `json:"prcorder_without_warehouse_location"`
		PrcorderWithoutWeight                                            string      `json:"prcorder_without_weight"`
		PrcordersEnablePartialFulfilling                                 string      `json:"prcorders_enable_partial_fulfilling"`
		PriceDecimals                                                    json.Number `json:"price_decimals"`
		PricelistZeroPriceAlgorithmUpdated                               string      `json:"pricelist_zero_price_algorithm_updated"`
		PrintCustomerRegcodeOnInvoice                                    string      `json:"print_customer_regcode_on_invoice"`
		PrintCustomerRewardPointsOnReceipt                               string      `json:"print_customer_reward_points_on_receipt"`
		PrintGiftcardBalanceOnReceipt                                    string      `json:"print_giftcard_balance_on_receipt"`
		ProcessingFeeAmex                                                string      `json:"processing_fee_amex"`
		ProcessingFeeDebit                                               string      `json:"processing_fee_debit"`
		ProcessingFeeDiscover                                            string      `json:"processing_fee_discover"`
		ProcessingFeeMc                                                  string      `json:"processing_fee_mc"`
		ProcessingFeeVisa                                                string      `json:"processing_fee_visa"`
		ProdmoveWithSalesprice                                           string      `json:"prodmove_with_salesprice"`
		ProductCode2Automatic                                            string      `json:"product_code2_automatic"`
		ProductCode2Unique                                               string      `json:"product_code2_unique"`
		ProductCodeUnique                                                string      `json:"product_code_unique"`
		ProductFamiliesRightsInitialized                                 string      `json:"product_families_rights_initialized"`
		ProductHistoryNumberOfLocationsShown                             string      `json:"product_history_number_of_locations_shown"`
		ProductNamesEditableOnInvoice                                    string      `json:"product_names_editable_on_invoice"`
		ProductSearchReturnsMatrixAndVariations                          string      `json:"product_search_returns_matrix_and_variations"`
		PromotionTiersRightsInitialized                                  string      `json:"promotion_tiers_rights_initialized"`
		QbExportFileID                                                   string      `json:"qbExportFileID"`
		QbAccountsReceivableTrade                                        string      `json:"qb_accounts_receivable_trade"`
		QbCashOverAndShort                                               string      `json:"qb_cash_over_and_short"`
		QbCountedOverShortAmounts                                        string      `json:"qb_counted_over_short_amounts"`
		QbCreditDefault                                                  string      `json:"qb_credit_default"`
		QbDebitDefault                                                   string      `json:"qb_debit_default"`
		QbInventory                                                      string      `json:"qb_inventory"`
		QbSalesAndUseTaxPayable                                          string      `json:"qb_sales_and_use_tax_payable"`
		QuickbooksIncludeSameDayInvoicesAndPayments                      string      `json:"quickbooks_include_same_day_invoices_and_payments"`
		Quickpos                                                         string      `json:"quickpos"`
		ReceiptLogoURL                                                   string      `json:"receiptLogoURL"`
		ReceiptDiscountDecimals                                          string      `json:"receipt_discount_decimals"`
		ReceiptFooter                                                    string      `json:"receipt_footer"`
		ReceiverSignatureOnInvoice                                       string      `json:"receiver_signature_on_invoice"`
		RefNo                                                            string      `json:"ref_no"`
		RemakeBillingInvoiceIfCredited                                   string      `json:"remake_billing_invoice_if_credited"`
		ReportGeneratorRightsUpdated                                     string      `json:"report_generator_rights_updated"`
		ReverseVatText                                                   string      `json:"reverse_vat_text"`
		RewardPointsDecimals                                             string      `json:"reward_points_decimals"`
		RewardPointsDuration                                             string      `json:"reward_points_duration"`
		RewardPointsIsDouble                                             string      `json:"reward_points_is_double"`
		RewardPointsPerCurrencyUnit                                      string      `json:"reward_points_per_currency_unit"`
		SalesDocumentStartNumber                                         string      `json:"sales_document_start_number"`
		SalonBookingCharge1Channel                                       string      `json:"salon_booking_charge1_channel"`
		SalonBookingCharge1Service                                       string      `json:"salon_booking_charge1_service"`
		SalonBookingCharge2Channel                                       string      `json:"salon_booking_charge2_channel"`
		SalonBookingCharge2Service                                       string      `json:"salon_booking_charge2_service"`
		SalonBookingCharge3Channel                                       string      `json:"salon_booking_charge3_channel"`
		SalonBookingCharge3Service                                       string      `json:"salon_booking_charge3_service"`
		SalonBookingEmailOrPhoneRequired                                 string      `json:"salon_booking_email_or_phone_required"`
		SalonBookingEmailRequired                                        string      `json:"salon_booking_email_required"`
		SalonBookingInAdvanceMax                                         string      `json:"salon_booking_in_advance_max"`
		SalonBookingInAdvanceMin                                         string      `json:"salon_booking_in_advance_min"`
		SalonBookingPhoneRequired                                        string      `json:"salon_booking_phone_required"`
		SalonCancellationDeadline                                        string      `json:"salon_cancellation_deadline"`
		SalonCancellationFee                                             string      `json:"salon_cancellation_fee"`
		SalonCancellationService                                         string      `json:"salon_cancellation_service"`
		SalonCustomersCanBookAppointments                                string      `json:"salon_customers_can_book_appointments"`
		SalonRequireCreditCardForOnlineBooking                           string      `json:"salon_require_credit_card_for_online_booking"`
		SalonRequireCreditCardForPhoneBooking                            string      `json:"salon_require_credit_card_for_phone_booking"`
		SearchProductByCode4                                             string      `json:"search_product_by_code4"`
		SearchProductByCode5                                             string      `json:"search_product_by_code5"`
		SendInvoiceToEmailLabel                                          string      `json:"sendInvoiceToEmailLabel"`
		SendInvoiceToReceiverOrPayerEmail                                string      `json:"sendInvoiceToReceiverOrPayerEmail"`
		SendEmailsFromCompanyAddress                                     string      `json:"send_emails_from_company_address"`
		ServicesDisabled                                                 string      `json:"services_disabled"`
		ShowCodeXOnPackListDoc                                           string      `json:"showCodeXOnPackListDoc"`
		ShowAttendantsOnReceipt                                          string      `json:"show_attendants_on_receipt"`
		ShowCardPaymentsBasicInfoOnReceipt                               string      `json:"show_card_payments_basic_info_on_receipt"`
		ShowCardPaymentsOnReceipt                                        string      `json:"show_card_payments_on_receipt"`
		ShowCompanyLoyaltyCardCodeOnReceipt                              string      `json:"show_company_loyalty_card_code_on_receipt"`
		ShowCompanyNameInTitleBar                                        string      `json:"show_company_name_in_title_bar"`
		ShowCreditInUnpaidInvoicesReport                                 string      `json:"show_credit_in_unpaid_invoices_report"`
		ShowCurrencyRateOnReceipt                                        string      `json:"show_currency_rate_on_receipt"`
		ShowCustomerCompanyIDOnReceipt                                   string      `json:"show_customer_company_id_on_receipt"`
		ShowCustomerPersonIDOnReceipt                                    string      `json:"show_customer_person_id_on_receipt"`
		ShowDebitButtonOnPos                                             string      `json:"show_debit_button_on_pos"`
		ShowManualDiscount                                               string      `json:"show_manual_discount"`
		ShowOriginalPriceOnReceipt                                       string      `json:"show_original_price_on_receipt"`
		ShowPersonLoyaltyCardCodeOnReceipt                               string      `json:"show_person_loyalty_card_code_on_receipt"`
		ShowPriceListDiscount                                            string      `json:"show_price_list_discount"`
		ShowPriceWithVat                                                 string      `json:"show_price_with_vat"`
		ShowPromotionDiscount                                            string      `json:"show_promotion_discount"`
		ShowReasonCodeOnReceipt                                          string      `json:"show_reason_code_on_receipt"`
		ShowRedeemedCouponsOnReceipt                                     string      `json:"show_redeemed_coupons_on_receipt"`
		ShowRetailCalculationAlgorithmPrices                             string      `json:"show_retail_calculation_algorithm_prices"`
		ShowRowCurrencyOnInvoice                                         string      `json:"show_row_currency_on_invoice"`
		ShowSalesPricePerStoreOnProductCard                              string      `json:"show_sales_price_per_store_on_product_card"`
		ShowShorterBalanceStatement                                      string      `json:"show_shorter_balance_statement"`
		ShowTaxExemptNumberOnReceipt                                     string      `json:"show_tax_exempt_number_on_receipt"`
		ShowTotalDiscountOnReceipt                                       string      `json:"show_total_discount_on_receipt"`
		SortPackinglistBy                                                string      `json:"sort_packinglist_by"`
		SortPackinglistByProductCodes                                    string      `json:"sort_packinglist_by_product_codes"`
		StockReplenishmentCreatesOneOrder                                string      `json:"stock_replenishment_creates_one_order"`
		StoreManagerSettingsRightsInitialized                            string      `json:"store_manager_settings_rights_initialized"`
		StorecreditEnabledOnSalepointCard                                string      `json:"storecredit_enabled_on_salepoint_card"`
		SupplierFieldUsedForSynchronization                              string      `json:"supplier_field_used_for_synchronization"`
		TablesizeActivity                                                string      `json:"tablesize_activity"`
		TablesizeActivityUpdated                                         string      `json:"tablesize_activity_updated"`
		TablesizeAdrtype                                                 string      `json:"tablesize_adrtype"`
		TablesizeAdrtypeUpdated                                          string      `json:"tablesize_adrtype_updated"`
		TablesizeAttributes                                              string      `json:"tablesize_attributes"`
		TablesizeAttributesUpdated                                       string      `json:"tablesize_attributes_updated"`
		TablesizeCampaign                                                string      `json:"tablesize_campaign"`
		TablesizeCampaignUpdated                                         string      `json:"tablesize_campaign_updated"`
		TablesizeCashorder                                               string      `json:"tablesize_cashorder"`
		TablesizeCashorderUpdated                                        string      `json:"tablesize_cashorder_updated"`
		TablesizeClock                                                   string      `json:"tablesize_clock"`
		TablesizeClockUpdated                                            string      `json:"tablesize_clock_updated"`
		TablesizeCoupon                                                  string      `json:"tablesize_coupon"`
		TablesizeCouponIssued                                            string      `json:"tablesize_coupon_issued"`
		TablesizeCouponIssuedUpdated                                     string      `json:"tablesize_coupon_issued_updated"`
		TablesizeCouponUpdated                                           string      `json:"tablesize_coupon_updated"`
		TablesizeCurrency                                                string      `json:"tablesize_currency"`
		TablesizeCurrencyUpdated                                         string      `json:"tablesize_currency_updated"`
		TablesizeInventory                                               string      `json:"tablesize_inventory"`
		TablesizeInventoryUpdated                                        string      `json:"tablesize_inventory_updated"`
		TablesizeInvoice                                                 string      `json:"tablesize_invoice"`
		TablesizeInvoiceUpdated                                          string      `json:"tablesize_invoice_updated"`
		TablesizeInvpaytype                                              string      `json:"tablesize_invpaytype"`
		TablesizeInvpaytypeUpdated                                       string      `json:"tablesize_invpaytype_updated"`
		TablesizeMatrixDimension                                         string      `json:"tablesize_matrix_dimension"`
		TablesizeMatrixDimensionUpdated                                  string      `json:"tablesize_matrix_dimension_updated"`
		TablesizeOrgper                                                  string      `json:"tablesize_orgper"`
		TablesizeOrgperUpdated                                           string      `json:"tablesize_orgper_updated"`
		TablesizePayment                                                 string      `json:"tablesize_payment"`
		TablesizePaymentUpdated                                          string      `json:"tablesize_payment_updated"`
		TablesizePaymenttype                                             string      `json:"tablesize_paymenttype"`
		TablesizePaymenttypeUpdated                                      string      `json:"tablesize_paymenttype_updated"`
		TablesizePointofsale                                             string      `json:"tablesize_pointofsale"`
		TablesizePointofsaleUpdated                                      string      `json:"tablesize_pointofsale_updated"`
		TablesizePrcinvoice                                              string      `json:"tablesize_prcinvoice"`
		TablesizePrcinvoiceUpdated                                       string      `json:"tablesize_prcinvoice_updated"`
		TablesizePricelist                                               string      `json:"tablesize_pricelist"`
		TablesizePricelistUpdated                                        string      `json:"tablesize_pricelist_updated"`
		TablesizeProdamort                                               string      `json:"tablesize_prodamort"`
		TablesizeProdamortUpdated                                        string      `json:"tablesize_prodamort_updated"`
		TablesizeProdamorttype                                           string      `json:"tablesize_prodamorttype"`
		TablesizeProdamorttypeUpdated                                    string      `json:"tablesize_prodamorttype_updated"`
		TablesizeProdin                                                  string      `json:"tablesize_prodin"`
		TablesizeProdinUpdated                                           string      `json:"tablesize_prodin_updated"`
		TablesizeProdmove                                                string      `json:"tablesize_prodmove"`
		TablesizeProdmoveUpdated                                         string      `json:"tablesize_prodmove_updated"`
		TablesizeProdpriority                                            string      `json:"tablesize_prodpriority"`
		TablesizeProdpriorityUpdated                                     string      `json:"tablesize_prodpriority_updated"`
		TablesizeProduct                                                 string      `json:"tablesize_product"`
		TablesizeProductExtraField1                                      string      `json:"tablesize_product_extra_field1"`
		TablesizeProductExtraField1Updated                               string      `json:"tablesize_product_extra_field1_updated"`
		TablesizeProductProduct                                          string      `json:"tablesize_product_product"`
		TablesizeProductProductUpdated                                   string      `json:"tablesize_product_product_updated"`
		TablesizeProductRecipe                                           string      `json:"tablesize_product_recipe"`
		TablesizeProductRecipeUpdated                                    string      `json:"tablesize_product_recipe_updated"`
		TablesizeProductUpdated                                          string      `json:"tablesize_product_updated"`
		TablesizePromotionTier                                           string      `json:"tablesize_promotion_tier"`
		TablesizePromotionTierUpdated                                    string      `json:"tablesize_promotion_tier_updated"`
		TablesizeSalepoint                                               string      `json:"tablesize_salepoint"`
		TablesizeSalepointUpdated                                        string      `json:"tablesize_salepoint_updated"`
		TablesizeSupplierPricelist                                       string      `json:"tablesize_supplier_pricelist"`
		TablesizeSupplierPricelistUpdated                                string      `json:"tablesize_supplier_pricelist_updated"`
		TablesizeTask                                                    string      `json:"tablesize_task"`
		TablesizeTaskUpdated                                             string      `json:"tablesize_task_updated"`
		TablesizeUser                                                    string      `json:"tablesize_user"`
		TablesizeUserUpdated                                             string      `json:"tablesize_user_updated"`
		TablesizeUsergroup                                               string      `json:"tablesize_usergroup"`
		TablesizeUsergroupUpdated                                        string      `json:"tablesize_usergroup_updated"`
		TablesizeVatrate                                                 string      `json:"tablesize_vatrate"`
		TablesizeVatrateUpdated                                          string      `json:"tablesize_vatrate_updated"`
		TablesizeWarehouse                                               string      `json:"tablesize_warehouse"`
		TablesizeWarehouseUpdated                                        string      `json:"tablesize_warehouse_updated"`
		ThumbImageDir                                                    string      `json:"thumb_image_dir"`
		ThumbUse                                                         string      `json:"thumb_use"`
		ThumbX                                                           string      `json:"thumb_x"`
		ThumbY                                                           string      `json:"thumb_y"`
		Timezone                                                         string      `json:"timezone"`
		TotalDiscountInformation                                         string      `json:"total_discount_information"`
		TotalDiscountLabelEng                                            string      `json:"total_discount_label_eng"`
		TouchPOSAllowOfflineLogin                                        string      `json:"touchpos_allow_offline_login"`
		TouchPOSAllowOfflineMode                                         string      `json:"touchpos_allow_offline_mode"`
		TouchPOSAlwaysOpenDrawerAfterSale                                string      `json:"touchpos_always_open_drawer_after_sale"`
		TouchPOSAutocloseCheckoutFinalConfirmatonPopup                   string      `json:"touchpos_autoclose_checkout_final_confirmaton_popup"`
		TouchPOSAutoidleAfterSale                                        string      `json:"touchpos_autoidle_after_sale"`
		TouchPOSCustomCouponTemplate                                     string      `json:"touchpos_custom_coupon_template"`
		TouchPOSCustomCSS                                                string      `json:"touchpos_custom_css"`
		TouchPOSDisableDefaultPrintTheReceipt                            string      `json:"touchpos_disable_default_print_the_receipt"`
		TouchPOSDisableExternalCardPayment                               string      `json:"touchpos_disable_external_card_payment"`
		TouchPOSDisableProductRowAutoOpen                                string      `json:"touchpos_disable_product_row_auto_open"`
		TouchPOSEnableCustomerDisplayApplication                         string      `json:"touchpos_enable_customer_display_application"`
		TouchPOSEnableLocalServerPrint                                   string      `json:"touchpos_enable_local_server_print"`
		TouchPOSEnableSvipeBox                                           string      `json:"touchpos_enable_svipe_box"`
		TouchPOSEodNotesRequired                                         string      `json:"touchpos_eod_notes_required"`
		TouchPOSExactCodeMatchAddsProductToTicket                        string      `json:"touchpos_exact_code_match_adds_product_to_ticket"`
		TouchPOSHideCommission                                           string      `json:"touchpos_hide_commission"`
		TouchPOSHideEmployeeStats                                        string      `json:"touchpos_hide_employee_stats"`
		TouchPOSJavascriptPluginPath                                     string      `json:"touchpos_javascript_plugin_path"`
		TouchPOSRemovePendingSalesBeforeCloseDay                         string      `json:"touchpos_remove_pending_sales_before_close_day"`
		TouchPOSSearchProductCodeFromMiddle                              string      `json:"touchpos_search_product_code_from_middle"`
		TouchPOSUIConfiguration                                          string      `json:"touchpos_ui_configuration"`
		TouchPOSUseDarkTheme                                             string      `json:"touchpos_use_dark_theme"`
		TouchscreenPos                                                   string      `json:"touchscreen_pos"`
		TouchscreenPosVersion                                            string      `json:"touchscreen_pos_version"`
		TransportInfoOnInvoices                                          string      `json:"transport_info_on_invoices"`
		UnpaidInvoicesReportsRightsUpdated                               string      `json:"unpaid_invoices_reports_rights_updated"`
		UseAttendantsInPos                                               string      `json:"use_attendants_in_pos"`
		UseDefaultLanguage                                               string      `json:"use_default_language"`
		UseFifoTracking                                                  string      `json:"use_fifo_tracking"`
		UseInvInvTable                                                   string      `json:"use_inv_inv_table"`
		UseM2Calculator                                                  string      `json:"use_m2_calculator"`
		UseMatrixPriceInPricelist                                        string      `json:"use_matrix_price_in_pricelist"`
		UsePurchaseWaybills                                              string      `json:"use_purchase_waybills"`
		UseStandaloneCustomerRegistry                                    string      `json:"use_standalone_customer_registry"`
		UseTransportCosts                                                string      `json:"use_transport_costs"`
		VatNumberAlwaysOnInvoice                                         string      `json:"vat_number_always_on_invoice"`
		Vertical                                                         string      `json:"vertical"`
		ViewImageDir                                                     string      `json:"view_image_dir"`
		ViewUse                                                          string      `json:"view_use"`
		ViewX                                                            string      `json:"view_x"`
		ViewY                                                            string      `json:"view_y"`
		WarehouseFixed2                                                  string      `json:"warehouse_fixed2"`
		WarehouseTransferOrderRemovesItems                               string      `json:"warehouse_transfer_order_removes_items"`
		WarehouseTransferReservesGoods                                   string      `json:"warehouse_transfer_reserves_goods"`
		WebImageDir                                                      string      `json:"web_image_dir"`
		WebUse                                                           string      `json:"web_use"`
		WebX                                                             string      `json:"web_x"`
		WebY                                                             string      `json:"web_y"`
		WeightsOnInvoices                                                string      `json:"weights_on_invoices"`
		WorkOrderText                                                    string      `json:"workorderText"`
		Xerokey                                                          string      `json:"xerokey"`
		ZReportHideDrawerOpenings                                        string      `json:"zreport_hide_drawer_openings"`
	}
	//GetConfParametersResponse ...
	GetConfParametersResponse struct {
		Status         common2.Status  `json:"status"`
		ConfParameters []ConfParameter `json:"records"`
	}
	Language struct {
		Name             string   `json:"name"`
		NativeName       string   `json:"nativeName"`
		ShortDisplayName string   `json:"shortDisplayName"`
		LegacyIdentifier string   `json:"legacyIdentifier"`
		IsoCode          string   `json:"isoCode"`
		Countries        []string `json:"countries"`
		IsOverride       bool     `json:"isOverride"`
	}
	GetDefaultLanguageResponse struct {
		Status    common2.Status `json:"status"`
		Languages []Language     `json:"records"`
	}
)
